module conquer.errors;

public {
  import conquer.errors.outofrangeexception;
}
